/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AfficherCalibres: typeof import('./../src/components/AfficherCalibres.vue')['default']
    AfficherCalibresV2: typeof import('./../src/components/AfficherCalibresV2.vue')['default']
    AfficherCulture: typeof import('./../src/components/AfficherCulture.vue')['default']
    AfficherDispos: typeof import('./../src/components/AfficherDispos.vue')['default']
    AfficherOrigines: typeof import('./../src/components/AfficherOrigines.vue')['default']
    AfficherProduits: typeof import('./../src/components/AfficherProduits.vue')['default']
    copy: typeof import('./../src/components/EntreeOrigine copy.vue')['default']
    EntreeCalibre: typeof import('./../src/components/EntreeCalibre.vue')['default']
    EntreeCulture: typeof import('./../src/components/EntreeCulture.vue')['default']
    EntreeDispo: typeof import('./../src/components/EntreeDispo.vue')['default']
    EntreeOrigine: typeof import('./../src/components/EntreeOrigine.vue')['default']
    EntreeProduit: typeof import('./../src/components/EntreeProduit.vue')['default']
    IMdiGithub: typeof import('~icons/mdi/github')['default']
    ITablerChevronDown: typeof import('~icons/tabler/chevron-down')['default']
    ITablerColorSwatch: typeof import('~icons/tabler/color-swatch')['default']
    ITablerLanguage: typeof import('~icons/tabler/language')['default']
    LeMenu: typeof import('./../src/components/LeMenu.vue')['default']
    Menu: typeof import('./../src/components/menu.vue')['default']
    PageCalibres: typeof import('./../src/components/PageCalibres.vue')['default']
    PageCultures: typeof import('./../src/components/PageCultures.vue')['default']
    PageDispos: typeof import('./../src/components/PageDispos.vue')['default']
    PageOrigines: typeof import('./../src/components/PageOrigines.vue')['default']
    PageProduits: typeof import('./../src/components/PageProduits.vue')['default']
    PageVentes: typeof import('./../src/components/PageVentes.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
